# -*- coding: utf-8 -*-
"""GrupoAura_Fase5_Cap1_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWwH5pcQqljCAZzmgI8QNP0U69Jq7qZM

# Relatório Acadêmico: Análise Comparativa de Arquiteturas de Deep Learning em Visão Computacional

## 1. Introdução e Objetivo do Projeto
O presente projeto visa resolver um problema clássico de Visão Computacional: a identificação automatizada de objetos em imagens. O objetivo principal é implementar, avaliar e comparar criticamente três diferentes abordagens de redes neurais, entendendo os cenários ideais de uso, a eficiência computacional e a precisão de cada arquitetura.

As abordagens avaliadas neste notebook são:
1. **YOLO Customizado (Fine-Tuning):** Adaptação do modelo YOLOv5 treinando-o com nosso próprio conjunto de dados em diferentes ciclos (30 e 60 épocas).
2. **YOLO Tradicional (Zero-Shot):** Utilização da arquitetura YOLOv5 padrão com pesos pré-treinados no dataset COCO.
3. **CNN do Zero (From Scratch):** Construção e treinamento de uma Rede Neural Convolucional clássica voltada exclusivamente para classificação binária.

## 2. Fundamentação Teórica

Antes da implementação, é crucial diferenciar as duas tarefas propostas:
* **Classificação de Imagens (CNN Clássica):** A rede recebe a imagem e retorna a probabilidade de ela pertencer a uma classe (Ex: "Isso é 90% Garrafa"). Ela não sabe *onde* a garrafa está, apenas que ela domina a imagem.
* **Detecção de Objetos (YOLO):** A rede prevê, em uma única passagem (You Only Look Once), não apenas a classe, mas as coordenadas exatas da *bounding box* (caixa delimitadora) para múltiplos objetos na mesma imagem.

## 3. Descrição do Dataset
Foi construído um dataset balanceado contendo 80 imagens de duas classes com geometrias muito distintas:
* **Garrafa** (Classe mais complexa devido a reflexos e transparências).
* **Celular** (Classe mais simples devido a bordas sólidas retangulares).

**Divisão (Split):** 64 imagens para Treino, 8 para Validação e 8 para Teste.
"""

# Importação das bibliotecas globais necessárias para os experimentos
import os
import glob
import time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image, display

# Bibliotecas específicas para CNN e Métricas
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing import image_dataset_from_directory
from sklearn.metrics import classification_report, confusion_matrix

# Conexão com o Google Drive para acessar o dataset
from google.colab import drive
drive.mount('/content/drive')

"""---
## Parte I: Detecção de Objetos com YOLOv5 Customizado

Nesta primeira etapa, vamos preparar o ambiente do YOLOv5 e executar nosso treinamento base. A ideia é treinar o modelo inicialmente por 30 épocas e, em seguida, dobrar o ciclo para 60 épocas, analisando se o modelo consolida o aprendizado ou se sofre de *overfitting* (memorização excessiva).
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone do repositório YOLOv5 e instalação de dependências
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -qr requirements.txt

# Criação do arquivo de configuração de classes (data.yaml)
import yaml
data_yaml = {
    'train': '/content/drive/MyDrive/dataset/train/images',
    'val': '/content/drive/MyDrive/dataset/valid/images',
    'test': '/content/drive/MyDrive/dataset/test/images',
    'nc': 2,
    'names': ['Garrafa', 'Celular']
}
with open('/content/drive/MyDrive/dataset/data.yaml', 'w') as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

from google.colab import drive
drive.mount('/content/drive')

"""### Execução dos Treinamentos (30 vs 60 Épocas)
Iniciando o processo de *Transfer Learning* utilizando os pesos do YOLOv5 pequeno (`yolov5s.pt`).
*(Nota: O tempo de treinamento na GPU T4 é de aproximadamente 3 a 6 minutos).*
"""

# Treinamento 1: 30 Épocas
!python train.py --img 640 --batch 16 --epochs 30 --data /content/drive/MyDrive/dataset/data.yaml --weights yolov5s.pt --name exp_30_epocas

# Treinamento 2: 60 Épocas
!python train.py --img 640 --batch 16 --epochs 60 --data /content/drive/MyDrive/dataset/data.yaml --weights yolov5s.pt --name exp_60_epocas

"""### Análise Imediata: Resultados do Treinamento Customizado

Observando as saídas das duas execuções acima, notamos uma evolução muito clara na capacidade de detecção da rede neural:

1. **Evolução do mAP (Mean Average Precision):** Em 30 épocas, o modelo alcançou um mAP@0.5 global de **0.810 (81%)**. Ao estender para 60 épocas, a rede consolidou as características visuais mais sutis e o mAP subiu para impressionantes **0.919 (91.9%)**.
2. **Dificuldade Geométrica:** A classe **Celular** atingiu rapidamente a excelência (mAP de 99.5% em 60 épocas). Já a classe **Garrafa** se mostrou um desafio; mesmo no pico de aprendizado, a rede apresentou um Recall de 62.7%, indicando uma postura conservadora (a rede prefere ignorar garrafas distorcidas a cometer falsos positivos).
3. **Overfitting Controlado:** A melhora generalizada e o salvamento automático do melhor peso (`best.pt`) garantem que o modelo escolhido para as próximas fases seja o mais apto a lidar com dados não vistos.

Abaixo, executamos a inferência deste melhor modelo (60 épocas) no conjunto de teste.
"""

# Inferência no conjunto de Teste com o YOLO customizado de 60 épocas
start_time = time.time()
!python detect.py --weights runs/train/exp_60_epocas/weights/best.pt --img 640 --conf 0.40 --source /content/drive/MyDrive/dataset/test/images --name exp_teste
tempo_custom = time.time() - start_time

print(f"\nTempo total de inferência no lote (Custom): {tempo_custom:.2f} segundos.")

# Exibindo os 3 primeiros resultados
imagens_processadas = glob.glob('/content/yolov5/runs/detect/exp_teste/*.jpg')
for nome_imagem in imagens_processadas[:3]:
    display(Image(filename=nome_imagem))
    print("\n")

"""---
## Parte II: Abordagem YOLO Tradicional (Out-of-the-Box)

Tendo estabelecido nosso modelo próprio como *baseline*, vamos testar o YOLOv5 tradicional. Ele será carregado diretamente com os pesos originais do dataset COCO. O dataset COCO possui 80 classes universais, e, por sorte, contém "bottle" e "cell phone".

Vamos avaliar como essa abordagem se comporta nas nossas imagens *sem nenhum treinamento adicional* (Tempo de treinamento = 0s).
"""

import torch

# Carregamento do modelo YOLOv5s original (pré-treinado no COCO)
model_yolo_tradicional = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Coletando imagens de teste
caminho_teste = '/content/drive/MyDrive/dataset/test/images/'
imagens_teste = [os.path.join(caminho_teste, f) for f in os.listdir(caminho_teste) if f.endswith('.jpg') or f.endswith('.png')]

# Inferência Medida
start_infer_trad = time.time()
resultados_trad = model_yolo_tradicional(imagens_teste)
end_infer_trad = time.time()

tempo_inferencia_trad = (end_infer_trad - start_infer_trad) / len(imagens_teste)

# Exibindo os resultados gerados pelo modelo padrão
resultados_trad.show()

print(f"Tempo médio de inferência por imagem (YOLO Tradicional): {tempo_inferencia_trad*1000:.2f} ms")

"""### Análise: YOLO Customizado vs YOLO Tradicional
O modelo tradicional se sai bem, mas exibe limitações inerentes. Por focar em 80 categorias simultaneamente, seu nível de confiança nas predições para nossas garrafas específicas pode ser menor. O **Customizado** ganha em precisão de nicho, pois os pesos da rede foram calibrados exclusivamente para a paleta de cores, iluminação e contexto das *nossas* 80 imagens.

---

## Parte III: Classificação de Imagens com CNN from Scratch

Para contrastar com a Detecção de Objetos (YOLO), agora implementaremos uma Classificação Clássica usando TensorFlow/Keras.
* **Problema:** A CNN não localiza objetos, ela olha para a imagem de 150x150 pixels e diz "Sim/Não" para a presença da classe.
* **Desafio:** Treinar uma rede profunda do absoluto zero com apenas 64 imagens é uma receita comum para *Overfitting*, onde a rede decora o treino e falha na validação.

> antes vamos reoganizar o dataset
"""

import os
import shutil

# 1. Definição dos caminhos de origem (YOLO) e destino (CNN)
# ATENÇÃO: Verifique se estes são os caminhos corretos no seu Google Drive
yolo_base_dir = '/content/drive/MyDrive/dataset'
cnn_base_dir = '/content/drive/MyDrive/dataset_cnn'

# 2. Dicionário mapeando o ID do YOLO para o nome da pasta
# Se no Make Sense AI você criou Garrafa primeiro e Celular depois, 0 é Garrafa.
classes_map = {'0': 'Garrafa', '1': 'Celular'}
splits = ['train', 'valid', 'test']

print("Iniciando a reorganização automática do dataset...")

for split in splits:
    labels_dir = os.path.join(yolo_base_dir, split, 'labels')
    images_dir = os.path.join(yolo_base_dir, split, 'images')

    # Verifica se a pasta do split existe
    if not os.path.exists(labels_dir) or not os.path.exists(images_dir):
        continue

    # Percorre todos os arquivos .txt (labels do YOLO)
    for label_file in os.listdir(labels_dir):
        if not label_file.endswith('.txt'):
            continue

        caminho_label = os.path.join(labels_dir, label_file)

        # Abre o arquivo .txt para ler a classe
        with open(caminho_label, 'r') as f:
            linha = f.readline().strip()
            # Se o arquivo estiver vazio (imagem sem anotação), ignora
            if not linha:
                continue

            # O formato YOLO é: <class_id> <x_center> <y_center> <width> <height>
            # Pegamos apenas o primeiro número (class_id)
            class_id = linha.split()[0]

        nome_classe = classes_map.get(class_id)
        if not nome_classe:
            continue

        # Prepara para buscar a imagem (troca .txt pela extensão da imagem)
        nome_imagem_base = os.path.splitext(label_file)[0]

        # Tenta encontrar a imagem correspondente (.jpg, .jpeg ou .png)
        caminho_img_origem = None
        for ext in ['.jpg', '.jpeg', '.png']:
            temp_path = os.path.join(images_dir, nome_imagem_base + ext)
            if os.path.exists(temp_path):
                caminho_img_origem = temp_path
                break

        if caminho_img_origem:
            # Cria a nova pasta de destino para a CNN: ex -> dataset_cnn/train/Garrafa/
            caminho_destino_dir = os.path.join(cnn_base_dir, split, nome_classe)
            os.makedirs(caminho_destino_dir, exist_ok=True)

            # Copia a imagem preservando os metadados
            caminho_img_destino = os.path.join(caminho_destino_dir, os.path.basename(caminho_img_origem))

            # Só copia se o arquivo ainda não existir no destino (evita retrabalho se rodar 2 vezes)
            if not os.path.exists(caminho_img_destino):
                shutil.copy2(caminho_img_origem, caminho_img_destino)

print(f"Sucesso! Dataset para a CNN criado estruturado na pasta: {cnn_base_dir}")

"""> seguimos com o treinamento


"""

# Configuração dos Diretórios para o Keras
# O Keras exige pastas separadas por classes (ex: test/Garrafa/img1.jpg)
# Assumimos que o dataset_cnn já possui esta estrutura no Drive.
base_dir = '/content/drive/MyDrive/dataset_cnn'

IMG_SIZE = (150, 150)
BATCH_SIZE = 16

train_dataset = image_dataset_from_directory(os.path.join(base_dir, 'train'), image_size=IMG_SIZE, batch_size=BATCH_SIZE)
val_dataset = image_dataset_from_directory(os.path.join(base_dir, 'valid'), image_size=IMG_SIZE, batch_size=BATCH_SIZE)
test_dataset = image_dataset_from_directory(os.path.join(base_dir, 'test'), image_size=IMG_SIZE, batch_size=BATCH_SIZE, shuffle=False)

# Arquitetura da CNN do Zero
model_cnn = models.Sequential([
    layers.Rescaling(1./255, input_shape=(150, 150, 3)),
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5), # Regularização para segurar o overfitting
    layers.Dense(1, activation='sigmoid') # Neurônio único para Binário (Garrafa=0, Celular=1)
])

model_cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Iniciando Treinamento e medindo o tempo
start_time_cnn = time.time()
history = model_cnn.fit(train_dataset, validation_data=val_dataset, epochs=30, verbose=1)
tempo_treino_cnn = time.time() - start_time_cnn

"""### Avaliação da CNN: Gráficos de Aprendizado e Inferência
Geramos as curvas de Loss e Acurácia para validar visualmente o comportamento da rede durante o treinamento, seguido pelo teste oficial.
"""

# Commented out IPython magic to ensure Python compatibility.
# Garante que os gráficos sejam plotados na própria célula do notebook
# %matplotlib inline
import matplotlib.pyplot as plt

# 1. Verifica quais métricas foram realmente salvas durante o treinamento
print("Métricas registradas pelo Keras:", history.history.keys())

# 2. Lida com a diferença de versão do TensorFlow dinamicamente
acc_key = 'accuracy' if 'accuracy' in history.history else 'acc'
val_acc_key = 'val_accuracy' if 'val_accuracy' in history.history else 'val_acc'

# 3. Extrai os dados
acc = history.history[acc_key]
val_acc = history.history[val_acc_key]
loss = history.history['loss']
val_loss = history.history['val_loss']

# Define o eixo X (número real de épocas que rodaram)
epochs_range = range(len(acc))

# 4. Criação da figura com design limpo e profissional
plt.figure(figsize=(14, 5))

# --- Gráfico de Acurácia ---
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Treinamento (Acc)', linewidth=2)
plt.plot(epochs_range, val_acc, label='Validação (Val Acc)', linewidth=2, linestyle='--')
plt.title('Evolução da Acurácia da CNN', fontsize=14)
plt.xlabel('Épocas', fontsize=12)
plt.ylabel('Acurácia', fontsize=12)
plt.legend(loc='lower right')
plt.grid(True, linestyle=':', alpha=0.7)

# --- Gráfico de Loss (Erro) ---
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Treinamento (Loss)', linewidth=2, color='red')
plt.plot(epochs_range, val_loss, label='Validação (Val Loss)', linewidth=2, linestyle='--', color='orange')
plt.title('Evolução do Erro (Loss) da CNN', fontsize=14)
plt.xlabel('Épocas', fontsize=12)
plt.ylabel('Loss (Entropia Cruzada)', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle=':', alpha=0.7)

# 5. Renderiza a imagem na tela
plt.tight_layout()
plt.show()

"""Para consolidar a análise de desempenho, submetemos a CNN ao nosso conjunto de teste isolado. A Matriz de Confusão abaixo ilustra os acertos e erros da rede em dados inéditos, evidenciando as limitações de capacidade de generalização do modelo quando treinado do zero com baixo volume de dados."""

import time
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Coletando predições e rótulos reais do conjunto de Teste
y_true = []
y_pred_probs = []

print("Iniciando inferência no conjunto de teste...")
start_infer_cnn = time.time()

for images, labels in test_dataset:
    y_true.extend(labels.numpy())
    # O model.predict retorna a probabilidade da classe ser 1 (Celular)
    preds = model_cnn.predict(images, verbose=0)
    y_pred_probs.extend(preds)

tempo_inferencia_cnn = (time.time() - start_infer_cnn) / len(y_true)

# 2. Convertendo probabilidades em classes binárias (Limiar de 0.5)
# Se a probabilidade for > 0.5, classificamos como 1 (Celular), senão 0 (Garrafa)
y_pred = [1 if prob > 0.5 else 0 for prob in y_pred_probs]

# 3. Gerando a Matriz de Confusão
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Garrafa (0)', 'Celular (1)'],
            yticklabels=['Garrafa (0)', 'Celular (1)'])

plt.title('Matriz de Confusão - CNN (From Scratch)', fontsize=14)
plt.ylabel('Classe Real', fontsize=12)
plt.xlabel('Classe Predita', fontsize=12)
plt.show()

# 4. Exibindo as métricas finais
print("\n" + "="*50)
print("RELATÓRIO DE CLASSIFICAÇÃO (CNN)")
print("="*50)
print(classification_report(y_true, y_pred, target_names=['Garrafa', 'Celular']))
print(f"Tempo médio de inferência por imagem (CNN): {tempo_inferencia_cnn*1000:.2f} ms")

"""---
## 4. Comparação Crítica e Relatório Técnico Final

Após desenhar, treinar e testar três arquiteturas distintas sob o mesmo escopo de dados, consolidamos a avaliação técnica do projeto:

| Abordagem | Tempo de Treinamento | Precisão Esperada | Inferência (Velocidade) | Complexidade de Uso |
| :--- | :--- | :--- | :--- | :--- |
| **1. YOLO Customizado** | Médio (~5-6 min) | **Alta (mAP > 91%)** | Rápida (~20ms/img) | Média (Exige anotação visual - bounding boxes) |
| **2. YOLO Tradicional** | **Imediato (0 min)** | Média (Viés do COCO) | Rápida (~20ms/img) | **Baixa (Apenas carregar pesos)** |
| **3. CNN do Zero** | Baixo (~1 min) | Baixa (Sofre Overfitting) | **Muito Rápida (~5ms/img)** | Alta (Exige formatação de pastas rigída) |

### Discussão dos Resultados

* **O Fracasso das CNNs com Poucos Dados:** A análise dos gráficos da CNN treinada do zero comprova que a técnica é inviável para datasets minúsculos. O gráfico de *Loss* demonstra que a rede rapidamente decora o conjunto de treinamento, fazendo com que a Acurácia de Validação estacione e sofra ruídos. Ela classifica, mas não sabe dizer *onde* está o objeto na imagem, o que a torna inútil para controle de esteiras de inventário, por exemplo.
* **O Dilema do Zero-Shot (YOLO Tradicional):** Usar o YOLO com pesos originais é a forma mais rápida de iniciar um projeto. No entanto, sua métrica é refém do dataset que originou os pesos. Se a FarmTech Solutions decidisse rastrear "Ferramentas Agrícolas Específicas" que não estão no COCO, essa rede falharia miseravelmente, provando que o Zero-Shot não é universal.
* **A Superioridade do Fine-Tuning (YOLO Customizado):** Nossa primeira abordagem provou ser a arquitetura vencedora do projeto. Ao aplicar transfer learning na espinha dorsal da rede e treiná-la por **60 épocas** com os nossos recortes exatos, alcançamos o equilíbrio ideal. O modelo reteve o aprendizado espacial rápido das redes de detecção e especializou seus filtros para o formato específico e os reflexos das nossas Garrafas e Celulares.

### Conclusão e Cenários de Recomendação
Concluímos que a escolha da arquitetura depende estritamente do cenário de negócio e da disponibilidade de dados:
* **Cenário de Produção Físico (Robótica/Webcam):** O **YOLO Customizado** é mandatório. Permite detecção espacial confiável para que braços mecânicos interajam com os objetos.
* **Cenário de Prototipagem Rápida:** O **YOLO Tradicional** atende bem como Prova de Conceito (PoC) inicial sem custo computacional.
* **Cenário de Triagem de Arquivos:** Uma **CNN** (se refinada com mais dados) serviria estritamente em sistemas de nuvem rodando scripts para separar rapidamente imagens "com celular" de imagens "sem celular" em um grande banco de dados, devido ao seu tempo ínfimo de inferência.
"""

